spring.thymeleaf.cache=false
server.error.include-exception=true
server.servlet.context-path=/


#==================== 日志配合·标准  ============================
logging.config=classpath:logback-boot.xml

logging.api.include-headers=Authorization,Content-Type  
logging.api.max-body-size=1024  